### ISSUE TITLE
[SUG] Better role management

### ISSUE THREAD

**Issue by TudbuT** [TudbuT/bottyclient#36]
(Example)

**Is your feature request related to a problem? Please describe.**
I can't edit roles.

**Describe the solution you'd like**
I want to be able to edit a role and also manage who belongs to the role. If possible, using buttons, so it's more visible.

**Describe alternatives you've considered**
I whould be okay with a text-based user and permission editor instead of a button-focused one.

**Additional context**
I don't have any.

**Credit**
Do you want to be credited: yes
If yes:
  Name: TudbuT#2624

**Comment by TudbuT** [comment]
This is an example.

(I will still add this but I don't have enough time atm)

**Comment by LoadxWar** [comment]
Hey this is illeagal
