### ISSUE TITLE
Commands

### ISSUE THREAD

**Issue by Sup-Sup123** [TudbuT/bottyclient#73]
Make it so you can use the commands that a Discord Moderation bot would consist of.

**Comment by TudbuT** [comment]
Okay! I'mma try to add that soon

**Comment by TudbuT** [comment]
There is one command already: /bc.i but that is not really a command. It only works in DMs and the only thing it does is displaying the User ID and Tag

**Comment by TudbuT** [comment]
I will probably do that tomorrow

**Comment by TudbuT** [comment]
Sorry! I forgot to do things! I will probably update soonish! News: https://discord.gg/J42bjuw

**Comment by TudbuT** [comment]
Ive now started doing this stuff!

**Comment by TudbuT** [comment]
i abandoned this now, since it should not be a full bot, just a client.
