### ISSUE TITLE
[SUG] Sharding Support

### ISSUE THREAD

**Issue by HPaulson** [TudbuT/bottyclient#74]
## Problem
- Currently, BottyClient has no support for sharding or sharded applications. This should be very possible in a clinet, and would be a great addition for larger applications attempting to use the client.

## Solution
- A solution to this is simple: Implement sharding. I'm not very familiar with the library in use, however I have heavy experience sharding with djs and eris, and am willing to help if needed for this addition.

## Errors
- When logging in with sharded bot:
`Error: This session would have handled too many guilds - Sharding is required.`

**Comment by TudbuT** [comment]
Oh! Okay! Since this is FATAL, imma do it asap!

**Comment by HPaulson** [comment]
Any updates on this addition?

**Comment by TudbuT** [comment]
Yes, I am still trying to implement it.

**Comment by Mikaru0Mystic** [comment]
im also interested

**Comment by TudbuT** [comment]
almost done, but have to do a lot for school atm. waiting for holidays, then ill be completing it

**Comment by TudbuT** [comment]
i have done this and tested it but sharding disables viewing the user list of a server (by default), so im gonna leave this as-is and close the issue! sorry for taking so long!
