### ISSUE TITLE
[BUG] Install Link Down

### ISSUE THREAD

**Issue by cr0121** [TudbuT/bottyclient#78]
curl -sSL https://dlbc.glitch.me/bcw | bash
https://dlbc.glitch.me/bcw is down
![Screenshot](https://user-images.githubusercontent.com/52645409/102102382-b3db1d80-3e66-11eb-9bb6-c979ca18b5e0.jpg)

**Comment by TudbuT** [comment]
Oh! Imma host a new link really quick

**Comment by TudbuT** [comment]
What platform are you on?

**Comment by TudbuT** [comment]
I updated the wiki, but im not sure if i still have access to the npm repo, imma look after that

**Comment by TudbuT** [comment]
Has been fixed and pushed to both github and npm! It might take a bit for the changes to apply.

**Comment by TudbuT** [comment]
Thanks!
