### ISSUE TITLE
[BUG] False Invalid token error

### ISSUE THREAD

**Issue by RainzDev** [TudbuT/bottyclient#80]
When I put the token in the valid token text box, it doesn't load the next page. When I checked the console, there was an error saying that the token is wrong even though it's the right one.

**Comment by TudbuT** [comment]
This is known, and you can ignore the infinite load, but i will still fix it if it bothers you.

**Comment by TudbuT** [comment]
Wait! So you entered a VALID token? (Please check that)

**Comment by TudbuT** [comment]
This problem is a discord.js problem, i cannot fix it.
