### ISSUE TITLE
[SUG] windows support

### ISSUE THREAD

**Issue by rubenh2905** [TudbuT/bottyclient#81]
my os is Windows 10 x64
npm ERR! notsup Unsupported platform for n@8.0.1: wanted {"os":"!win32"} (current: {"os":"win32","arch":"x64"})

**Comment by TudbuT** [comment]
Hello, did you use `npm install` or one of the .sh scripts? To use the main branch on windows, you have to use the `npm install` command. I will review package.json and remove "n" from the required deps.

**Comment by TudbuT** [comment]
(reopen if it still doesnt work)

**Comment by rubenh2905** [comment]
hello again, sorry for long delay
![image](https://user-images.githubusercontent.com/85017677/188095686-6c5e5ad7-d3f1-4072-96ef-be62fd7ebb2e.png)
as you can se it's trying to use bash command but it can't find it for some reason

**Comment by TudbuT** [comment]
can you run `echo $PATH ; which bash`?

**Comment by rubenh2905** [comment]
I'm using CMD, I don't think that command will work.
but after error on `npm install`, `npm start` will work.
oh another thing, this error is deferent with that old error.

**Comment by TudbuT** [comment]
so it does sorta work?

**Comment by rubenh2905** [comment]
in new version kinda yes
