### ISSUE TITLE
Add setActivity() function

### ISSUE THREAD

**Issue by Nguyenwasd72** [TudbuT/bottyclient#82]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add client.user.setActivity()

**Describe alternatives you've considered**
```js
// ./bot/main.js
// button:
"<button type=\"button\" onclick=\"window.location.href = `?path=setactivity&activity=${prompt('Activity:')}`\">setActivity</buttton>"
// function:
function setactivity(a) {
    if (a == "null" || a == "") return
    client.user.setActivity(a)
}
module.exports.setactivity = setactivity

// ./server.js
if (r.path === "setactivity" && r.activity) {
    bot.setactivity(r.activity)
    re.send(v + await bot.selectGuild() + style)
}
```

**Additional context**
I tested the function

**Credit**
Do you want to be credited:
Yes
Name: KNguyen#8442

**Comment by TudbuT** [comment]
This could be a pull request instead, but whatever. Merging.
