### ISSUE TITLE
Make a new line using \n

### ISSUE THREAD

**Issue by Nguyenwasd72** [TudbuT/bottyclient#83]
**Is your feature request related to a problem? Please describe.**
Maybe

**Describe the solution you'd like**
Replace "\n" to a new line

**Describe alternatives you've considered**
```js
// for function "send" (line 293)
await client.channels.cache.get(channel).send(msg.replace(/\\n/g, "\n"))
// for function "senddm" (line 308)
await client.users.cache.find(u => u.id === dm).send(msg.replace(/\\n/g, "\n"))
```

**Additional context**
[src](https://stackoverflow.com/questions/73419271/discord-js-n-doesnt-break-line-in-embed-description) i think

**Credit**
Do you want to be credited:
Yes:
Name: KNguyen#8442

**Comment by TudbuT** [comment]
Sure!
